### ISSUE TITLE
wallock seems to remain when leaving compositor

### ISSUE THREAD

**Issue by tyressk** [dpayne/wallock#11]
On initial release. Tried with Hyprland and Wayfire using `hyprctl dispatch exit`, and [wayland-logout](https://github.com/soreau/wayland-logout). Not sure about `dispatch exit`, but the latter should be sending a SIGTERM to the wayland socket. `loginctl kill-session` does work, though.

**Comment by dpayne** [comment]
It should be fixed in latest main branch.

This is a legit issue and a good find, thank you!
