### ISSUE TITLE
mpv decode does not appear to be using hardware decoding

### ISSUE THREAD

**Issue by kode54** [dpayne/wallock#12]
I am attempting to set up the Apple Aerial wallpapers, which I had to retrieve manually because Apple’s manifests changed and their server appears to be using its own signing authority now.

I have an AMD Radeon RX 6700 XT, and the videos are the 4k SDR set. I had to learn from the “Aerial” for MacOS project how to acquire the json describing the links, and instruct curl to use the -k switch.

Two displays playing videos is resulting in wallock using 150% of a core.

**Comment by dpayne** [comment]
Should be fixed in master, although I cannot test with AMD. For nvidia, this error hits more frequently when hardware rendering is enabled https://github.com/dpayne/wallock/blob/main/src/render/RendererMpv.cpp#L82 where it will cause the next video to load.

**Comment by kode54** [comment]
Thanks, that does indeed fix it. Though there's another issue I will report.
