### ISSUE TITLE
MPV resource loader does not appear to be rendering to the native resolution of scaled display

### ISSUE THREAD

**Issue by kode54** [dpayne/wallock#13]
I have a mixed DPI setup, where one display is 2.0 scale and the other is 1.0. It does not appear to be rendering the sourced 3840x2160 videos at the native resolution of the primary display. The same seems to go for the collection of UHD wallpapers I've collected from Bing daily rotation for over a year.

**Comment by dpayne** [comment]
should be fixed in main
