### ISSUE TITLE
[Feature request] Stop updating the wallpaper or at least lock screen for outputs which are turned off

### ISSUE THREAD

**Issue by kode54** [dpayne/wallock#14]
Maybe look into the interfaces used by `wlopm` or `wlr-randr` or by a compositor to watch for those state changes, to determine when it should be safe to stop updating the wallpaper for an output.

**Comment by dpayne** [comment]
This should be straight forward, I'll try to get to it today or tomorrow.

**Comment by dpayne** [comment]
This is fixed in the main branch with some qualifications. On different monitors I get different behaviors.

With my samsung monitor as soon as I turn it off a display remove event is triggered, on my LG monitor the event is not triggered when the monitor is manually turned off. For the LG monitor, since no removal event is trigger, the mpv instance is not stopped. This appears to happen on other apps as well (wdisplays still shows the LG monitor as available even thought it is physically unplugged).

I am closing this for now but please follow up if it does not work for you.

**Comment by kode54** [comment]
Just in case it's more useful:

https://git.sr.ht/~leon_plickat/wlopm/tree/master/item/wlopm.c

This demonstrates how to use several Wayland services to change the power mode, but most importantly, it shows how to register a listener service which will be notified when power modes have been changed, and how to poll the current state.

**Comment by dpayne** [comment]
I tried integrating both wlr-output-power-management and wlr-output-management with the associated listeners, neither get a signal when the LG monitor turns manually. Things seem to work with my samsung monitor so I suspect it is something related to the LG monitor.

If it is not working for you please let me know your setup and the specific make/models and I get try to debug some more.

**Comment by kode54** [comment]
Does this code exist in a branch somewhere? Maybe I can try to get it working.

The code which listens for registry items for output interfaces should be listening for new outputs, such as on hotplug. The sync callback should be used on first launch to register power management for each already-registered display, but I'm not sure how one registers on hotplugged displays. Either way, power management v1 should get_output_power on every new display, and dispose of that interface when it fails or becomes invalid, such as hot removal. The get_output_power also includes add_listener, and the listener will report on first connect and subsequent mode changes when the power mode changes. It will become invalid if the output hot disconnects.

wlopm demonstrates how to get it on first register, but the listeners need to stay registered for the life of an output, to continue receiving mode updates up until any hot disconnects.

This will work for at least my primary LG display, which hot disconnects and reconnects when it powers back on. The power mode off signal should be sent the moment the compositor or wlopm turn it off.

I can try to implement this, if I know which methods I should be invoking on an existing display to pause the mpv output, assuming pausing it will also pause the image cycling timer on static images.

**Comment by kode54** [comment]
Disregard the above. The protocol I found is only for configuring the outputs and polling their current state as a power management app. The only protocol that can listen for changes is either a server, via wlroots, or a client that is designed to change the state, and therefore has exclusive control over the protocol. There is no passive listener for polling the output state, and using the manager momentarily to poll the state could race with other tools trying to change the states.

Total dead end.
