### ISSUE TITLE
[Bug] mpv 0.38.0 update causes wallock to spawn normal windows instead of background frames

### ISSUE THREAD

**Issue by kode54** [dpayne/wallock#15]
Arch just updated this package today.

**Comment by kirkas** [comment]
Experiencing the same issue.

**Comment by ricjuhnl** [comment]
Same issue, still on version .38

`mpv --version
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 18 2024 06:31:17
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100`

**Comment by dpayne** [comment]
for a short term fix, forcing software rendering should work. I'll update today and debug.

**Comment by dpayne** [comment]
Fixed in latest main branch
