### ISSUE TITLE
[Feature Request] Query if screen is locked

### ISSUE THREAD

**Issue by kode54** [dpayne/wallock#17]
Is there any way to query if the screen locker is active from a shell script? There is a trick [here](https://github.com/swaywm/swaylock/pull/350#issuecomment-2026959921) for running swayidle such that it will do a long timeout when swaylock is not running, and a short timeout if it is running. Primarily used for DPMS power off within a short delay when the screen is locked.

**Comment by dpayne** [comment]
would this work for you https://github.com/dpayne/wallock/pull/21 ?

**Comment by dpayne** [comment]
Closing this since I merged the above change, let me know if it doesn't work for you
