### ISSUE TITLE
Breaks on Nvidia driver 560

### ISSUE THREAD

**Issue by kirkas** [dpayne/wallock#19]
I understand Nvidia support is unstable, but everything was working fine for me until I installed newest driver (560).

**Comment by dpayne** [comment]
I'll try this later today when I update. Do you mind posting the error you get and/or describing what is broken?

**Comment by dpayne** [comment]
A preliminary fix is here https://github.com/dpayne/wallock/pull/20/files note this is *NOT* well tested yet so use at your own risk. Once I have tested it more, I will merge it to main.

**Comment by dpayne** [comment]
this should be fixed in main, please let me know if you still have issues

**Comment by kirkas** [comment]
it worked! than you 🙏🏻
