### ISSUE TITLE
'wallock -o lock' crashes wallock

### ISSUE THREAD

**Issue by tyressk** [dpayne/wallock#8]
Just installed from AUR (r22.651c017-1). Running on wayfire.

Calling `wallock -o lock` stops the wallpaper and doesn't show any lock screen. I need to `killall wallock` (twice for some reason Edit: but `kill -9` kills it once), `rm /run/user/1000/wallock/wallock.sock` to be able to rerun wallock.

I set logs to trace and get these:

```
[2024-04-15 23:36:19.462] [wallock] [debug] [Wallock.cpp:123] Locking...
[2024-04-15 23:36:19.462] [wallock] [error] [Registry.cpp:103] Lock manager is not available
[2024-04-15 23:36:19.462] [wallock] [critical] [Display.cpp:79] Failed to get lock
```

Am I missing something?

**Comment by tyressk** [comment]
Just built from source and getting the same issue (tried just in case)

**Comment by dpayne** [comment]
I'll try to debug this later today. Does swaylock work for you in wayfire?

**Comment by dpayne** [comment]
Looks like wayfire implemented the session lock pretty recently, https://github.com/WayfireWM/wayfire/commit/2df26174e89fda44adebf5b78c60642cc0ae9118

It theoretically should work on the latest version of wayfire, although I did not test it. Please re-open if it does not work on the latest version of wayfire. I'll update the readme to include that it should require the compositor implement the session lock protocol.

**Comment by tyressk** [comment]
Hi @dpayne , yes I can confirm `swaylock` works for me and `wallock -o lock` does not. This is my  `wayfire --version` output: `0.8.1-26ed617 (Apr 10 2024) branch master`. It seems I am on the latest version of wayfire. I think the issue should be reopened

**Comment by dpayne** [comment]
If you are on latest wayfire, then loading the session-lock plugin in wayfire should work. This seemed to work on my laptop.

For swaylock, it looks like an older version did not rely on the session lock plugin, here is the comparison between master and the current released version on arch https://github.com/swaywm/swaylock/compare/v1.7.2...master#diff-a0cb465674c1b01a07d361f25a0ef2b0214b7dfe9412b7777f89add956da10ecL350 If you try swaylock from current head, then it will also fail without the session-lock plugin.

If there are enough compositors that do not implement session lock then I will implement the alternative way.

**Comment by tyressk** [comment]
Ah my mistake, I didn't realize the wayfire session-lock plugin wasn't on a release yet. Got it working. Thanks and looks awesome!
