### ISSUE TITLE
Feature request: Video on loop

### ISSUE THREAD

**Issue by kirkas** [dpayne/wallock#9]
Pretty much the title :)

I have a few videos that works well  when played in a loop, and I don't want wallock to automatically play to the next video when the current one is done playing.

Ideally this wouldn't trigger a new screenshot.

Thanks for the awesome work!

**Comment by dpayne** [comment]
this should be straight forward, I'll work on it soon

**Comment by dpayne** [comment]
```file_loop=true```

Added in the latest git version
